### ISSUE TITLE
For larger puzzles, it is difficult to count the length of blocks.

### ISSUE THREAD

**Issue by jeremypw** [jeremypw/gnonograms#15]
It would help to have a tool tip or other means to measure the length of the block(s) the cursor is on or the pointer is hovering.

**Comment by jeremypw** [comment]
I tried adding a tooltip to the cursor displaying the info but decided it was too distracting. Perhaps a status bar - but I do not think this accords with elementary design principles.

**Comment by freaktechnik** [comment]
what about making it some kind of toggleable mode? Where you can select horizontal/vertical block sizes to be displayed?

**Comment by jeremypw** [comment]
Yeah, maybe some kind of popup linked to a hotkey. 
I have a trial branch which makes the grid scrollable intended to make larger puzzles easier to manipulate

**Comment by jeremypw** [comment]
With randomly generated puzzles of a practical size (< 40?) blocks are rarely longer than 10 so this is not too much of a problem.  I do not know how often users load or design puzzles with blocks much longer than this.  Will wait for a user to raise this issue.
