### ISSUE TITLE
Error dialog on first run

### ISSUE THREAD

**Issue by cassidyjames** [jeremypw/gnonograms#2]
I got an error dialog on two different installs when I first run the app, saying something about it being unable to load a game. After closing it, the game is in a state of solving "undefined."

**Comment by cassidyjames** [comment]
Because of this issue, I've declined the current release. I'm happy to help debug and get a new release tested for you!

**Comment by cassidyjames** [comment]
I believe it was this error message: https://github.com/jeremypw/gnonograms/blob/d9fa5fa7201a7b66e8e4e7e28a236cef059e48ba/src/core/Gnonogram_filereader.vala#L75

**Comment by jeremypw** [comment]
I missed this because the uninstall script was not removing the user temporary game directory - so testing did not reproduce a clean install :-( . I can now reproduce this. Should be fixed soon.

**Comment by jeremypw** [comment]
Should be fixed by v1.0.4

**Comment by danirabbit** [comment]
I can confirm, no error dialog on first run :)
