### ISSUE TITLE
Uninstallable dependency  libgnonograms-core0

### ISSUE THREAD

**Issue by saidbakr** [jeremypw/gnonograms#35]
When I try to install it from the app store I got the following message:
```
The following packages have unmet dependencies:
  com.github.jeremypw.gnonograms: Depends: libgnonograms-core0 (= 1.4.2) but it is not installable
```
Elementary OS Hera.

**Comment by jeremypw** [comment]
Thanks for letting me know! Looks like something went wrong with the latest release :-( .  Probably worked during testing because I already had libgnonograms-core0 installed.   Will fix asap.

**Comment by jeremypw** [comment]
Looks like libgnonograms-core0 is not appearing in the repository for some reason.

**Comment by jeremypw** [comment]
It appears that there is an limitation with Houston which means that shared libraries cannot be used for third-party apps which is a shame - I am not sure where that is documented :-(  I was going to release another nonogram related app (gnonogram-tools) at some point which made use of that library.  Now I will have to re-engineer things to use a copy of that library statically in each app.

So the latest release will have to be withdrawn until that is done.  Sorry about that.

**Comment by jeremypw** [comment]
Its a bit like Flatpak etc where each app has its own copy of the libraries it uses.

**Comment by jeremypw** [comment]
New version now released
