### ISSUE TITLE
Provide a Flatpak as software package

### ISSUE THREAD

**Issue by x80486** [jeremypw/gnonograms#36]
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

---

I can help with the [initial manifest](https://github.com/x80486/flathub/tree/com.github.jeremypw.gnonograms/), creating the Pull Request for Flathub...and you folks take over maintenance :wink:

> If you decide to move forward with this one, there is one change to `data/meson.build:68` that's needed first. `appstreamcli` should be changed by `appstream-util`.

**Comment by jeremypw** [comment]
Thanks for the suggestion!  It is something I will investigate.

**Comment by jeremypw** [comment]
I have pushed a PR to Flathub which is being reviewed - https://github.com/flathub/flathub/pull/1653

**Comment by jeremypw** [comment]
Changing `appstreamcli` to `appstream-util` stopped the app compiling locally on Hera so I have removed that test for now in the Flatpak version.

**Comment by jeremypw** [comment]
Closed by the latest release
