### ISSUE TITLE
Make completed rows and columns visually distinct

### ISSUE THREAD

**Issue by freaktechnik** [jeremypw/gnonograms#7]
Some other nonogram applications grey out the numbers for completed rows or columns, which helps a lot, in my opinion. Some even start to grey out whenever you have fully marked to an edge of the field (so the first numbers or last numbers have been marked/isolated).

**Comment by jeremypw** [comment]
Thanks for taking the time to suggest this freaktechnik - all suggestions are welcome.  I appreciate there is still some UI tweaking to do and I will try to implement this in the next release.

**Comment by jeremypw** [comment]
Implementing greying out completed rows/cols is simple enough using "dim-label" style-class and will be in the next release.  Greying out individual blocks within the labels is more complicated so I will wait to see what support there is for this.

**Comment by jeremypw** [comment]
Fixed by 26d2c5305504a08d4961820cb6576b3a0aa8b106

**Comment by freaktechnik** [comment]
This works very nicely! Thank you!

**Comment by jeremypw** [comment]
Glad you like it :-)
